name: simpleprogram
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run python script
        run: python Ifelse.py
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run python script
        run: python Ifelse.py
      - name: Print Hi
        run: python hi.py
        
        
      
        
        
      
        
    
